import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${siliguri.className} ${geistSans.variable} ${geistMono.variable} font-sans antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
